#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int block = 2000;

task main()
{
	for (int i = 1; i <= 3; i++) {
		motor[port2] = 127;
		motor[port3] = 127;
		wait1Msec(block * i);
		motor[port2] = -127;
		motor[port3] = -127;
		wait1Msec(block * i);
	}
}
