#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int block = 2000;

task main()
{
	motor[port2] = 127;
	motor[port3] = 127;
	wait1Msec(2500);
	motor[port3] = -127;
  wait1Msec(630);
	motor[port3] = 127;
	wait1Msec(2900);
	motor[port2] = -127;
	wait1Msec(630);
	motor[port2] = 127;
	wait1Msec(2100);
	motor[port2] = -127;
	wait1Msec(630);
	motor[port2] = 127;
	wait1Msec(1300);
}
