#pragma config(StandardModel, "RVW Mammalbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma debuggerWindows("joystickSimple");
#include <JoystickDriver.c>

task main()
{
	while (true) {
		getJoystickSettings(joystick);
		int y2 = joystick.joy1_y2, y1 = joystick.joy1_y1;
		bool b2 = y2 >= 0, b1 = y1 >= 0;
		motor[port2] = (b2 == b1 ? y2 : y2 / 2);
		motor[port3] = (b2 == b1 ? y1 : y1 / 2);
	}
}
