#pragma config(StandardModel, "RVW Mammalbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma debuggerWindows("joystickSimple");
#include <JoystickDriver.c>

task main()
{
	while (true) {
		getJoystickSettings(joystick);
		motor[port2] = joystick.joy1_y2;
		motor[port3] = joystick.joy1_y1;
	}
}
