#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool first = true;
	while (true) {
		motor[port2] = 127;
		motor[port3] = 127;
		wait1Msec(first ? 3100 : 3500);
		first = false;
		motor[port2] = -127;
		wait1Msec(630);
	}
}
