#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[port2] = -127;
	motor[port3] = 127;
	wait1Msec(630 * 2);
	motor[port3] = -127;
	wait1Msec(4000);
}
