#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma debuggerWindows("joystickSimple");
#include <JoystickDriver.c>

task main()
{
	while (true) {
		getJoystickSettings(joystick);
		int x = joystick.joy1_TopHat;
		if (x == 0) {
			motor[port2] = 127;
			motor[port3] = 127;
			wait1Msec(1475);
			motor[port2] = 0;
			motor[port3] = 0;
		} else if (x == 6) {
			motor[port2] = 127;
			motor[port3] = -127;
			wait1Msec(625);
			motor[port2] = 0;
			motor[port3] = 0;
		} else if (x == 2) {
			motor[port2] = -127;
			motor[port3] = 127;
			wait1Msec(625);
			motor[port2] = 0;
			motor[port3] = 0;
		}
	}
}
